### ISSUE TITLE
Quotes

### ISSUE THREAD

**Issue by openkey** [grvcoelho/css#2]
Quotes

Quotes are optional in CSS. You should use single quotes as it is visually clearer that the string is not a selector or a style property.

/\* wrong _/
.avatar {
  background-image: url('/img/you.jpg');
  font-family: 'Helvetica Neue Light', Helvetica Neue, Helvetica, Arial;
}
/_ right */
.avatar {
  background-image: url(/img/you.jpg);
  font-family: Helvetica Neue Light, Helvetica Neue, Helvetica, Arial;
}

The "right" answer and "wrong" answer are switched based off of "You should use single quotes..."

**Comment by grvcoelho** [comment]
Fixed!
